spring:
  jpa:
    database: oracle
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.Oracle12cDialect
  datasource:
    username: EBANK_SBU #rmunialo
    url: jdbc:oracle:thin:@10.20.2.151:1521/ekenyaoracle
    password: Pass123 #rMunialo@123
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 20
      pool-name: api-db-pool
      minimum-idle: 3
  application:
    name: db-api-spring
server:
  tomcat:
    accept-count: 200
    max-connections: 8192
    max-threads: 200
  port: 6501
  ssl:
      key-store: classpath:sslkeystore.p12
      enabled: false
      key-store-type: PKCS12
      key-store-password: mypass
      key-alias: tomcat
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    secure-port-enabled: true
#    secure-port: ${server.port}

primarydb: oracle
schema-name: EBANK

file-storage:
  sp-location: configs/sp-list.json
  query-template: configs/query-template.json
  sql-queries: configs/sql-queries.json

whitelist-ip: localhost, 10.20.2.59
whitelist-ip-encrypted: pXJW4UnYEHmRmWDaaoMKlw==, PfDO/ivsKPeh9SsehgShPA==